channels:
  - conda-forge
  - defaults
dependencies:
  - conda
  - jupyter
  - ipykernel 
  - pandas
  - numpy
  - nbformat
  - xlrd
  - openpyxl
  - xlsxwriter
  - seaborn
  - statsmodels
  - scipy==1.2
  - pip
  - pip:
    - cython
